### ISSUE TITLE
Calculate Average Rating for Recipes

### ISSUE THREAD

**Issue by Kenneth-Ngcobo** [ElzabeEls/ASE_2024_GROUP_B#246]
As a backend developer, I want to ensure that the system calculates the average rating for each recipe based on user reviews, so that the recommendations reflect the most popular recipes.
This logic should run whenever a new review is added or an existing review is edited or deleted, ensuring that the average rating is always up-to-date for the recommendation endpoint.

**Comment by OmphileMorwane** [comment]
Worked on the wrong branch:

![image](https://github.com/user-attachments/assets/c752dcc2-af14-4791-a4f2-d4cfcc7e55f6)
